$ANSIBLE_VAULT;1.1;AES256
37353636653031626336336134303536346339373263313437636262613031343438393737393762
3838366461626239313739633531633739633032313361310a666661313162333035396238343531
33376261613831353830323033336431356434623237613165313139326466383338306565366265
3630643432643064390a646332646133636137303763346139346561353863386535346537633135
30613936396130646433663237656134633961333237646532303131393161633562376639313036
62666561323831313531333836323936653134346438306431303630663661393435396238326563
39623263323462316631356333303830653532326339386336343136396533623666313334363839
66326365613663643765623661666163636431663439346331353730393463623463643862316434
32356164373261376362666339646233656335306264376466336165346132316637663164613064
37626432653037306235613965653262323062373134336438656366353563373233653233333136
336339613834303363633537383762623864
